import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/main.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio Website",
  description: "Generated by ToolAura🚀",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
            {children}
        </body>
      </html>
    </>
  )
}