import "./globals.css";
import "./styles/main.css";

export const metadata = {
  title: "Portfolio Website",
  description: "Generated by ToolAura🚀",
  icons: {
    icon: "/favicon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
            {children}
        </body>
      </html>
    </>
  )
}